"""empty message

Revision ID: 3b0291a9e840
Revises: a4d11d7a2981
Create Date: 2022-01-19 15:03:11.277695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0291a9e840'
down_revision = 'a4d11d7a2981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_number', sa.Integer(), nullable=False))
    op.drop_column('games', 'team_two')
    op.drop_column('games', 'team_one')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('team_one', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('team_two', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('games', 'game_number')
    # ### end Alembic commands ###
