"""empty message

Revision ID: 86808b2bba02
Revises: 69f4dc3cc2e3
Create Date: 2022-01-28 12:22:07.705898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86808b2bba02'
down_revision = '69f4dc3cc2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'date')
    # ### end Alembic commands ###
