"""empty message

Revision ID: 69f4dc3cc2e3
Revises: eeb1787ad04f
Create Date: 2022-01-27 19:38:35.606097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f4dc3cc2e3'
down_revision = 'eeb1787ad04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chirp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chirp_id'], ['chirps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
